#!/bin/bash

set -e

IFS='' read -r -d 'EOF'  usage <<END

$(basename $0) [--console]

Launch the HVM on XCP-ng

EOF
END

die() {
	echo "$@" >&2
	exit 1
}

[[ "$@" =~ "--help" ]] && die "${usage}"


use_console=0
[[ "$@" =~ "--console" ]] && {
    use_console=1
}

VM_ID=$(cat ./.hvmtool-vm-uuid)
xe vm-start uuid=${VM_ID}

if [[ "${use_console}" == "1" ]]; then
    DOM_ID=$(xe vm-param-get uuid=${VM_ID} param-name=dom-id)
    PTY=$(xenstore-read /local/domain/${DOM_ID}/serial/0/tty)
    screen ${PTY}
    #xl console $DOM_ID
fi
