#!/bin/bash

set -e

IFS='' read -r -d 'EOF'  usage <<END

$(basename $0) <vm-uuid> <attach-console>

Launch an HVM on XCP-ng

vm-uuid: The XAPI VM uuid
EOF
END

die() {
	echo "$@" >&2
	exit 1
}

[[ "$#" != "2" ]] && {
	die "${usage}"
}

[[ "$@" =~ "help" ]] && die ${usage}

xe vm-start uuid=$1

if [[ "$2" != "0" ]]; then
    DOM_ID=$(xe vm-param-get uuid=$1 param-name=dom-id)
    PTY=$(xenstore-read /local/domain/${DOM_ID}/serial/0/tty)
    screen ${PTY}
fi
