#!/bin/bash

set -e

IFS='' read -r -d 'EOF'  usage <<END

$(basename $0) <vm-uuid>

Launch a gdbsx session with guest

vm-uuid: The XAPI VM uuid
EOF
END

[[ "$#" != "1" ]] && {
	die "${usage}"
}

GUEST_BITWIDTH=64
DOM_ID=$(xe vm-param-get uuid=$1 param-name=dom-id)

gdbsx -a ${DOM_ID} ${GUEST_BITWIDTH} 9999
