#!/bin/bash

set -e

IFS='' read -r -d 'EOF'  usage <<END

$(basename $0) <vm-uuid>

Launch an HVM on XCP-ng

vm-uuid: The XAPI VM uuid
EOF
END

[[ "$#" != "1" ]] && {
	die "${usage}"
}

die() {
	echo "$@" >&2
	exit 1
}



xe vm-start uuid=$1
DOM_ID=$(xe vm-param-get uuid=$1 param-name=dom-id)
#xenstore-read /local/domain/34/console/tty
PTY=$(xenstore-read /local/domain/${DOM_ID}/serial/0/tty)

screen ${PTY}
