#!/bin/bash

set -e

IFS='' read -r -d 'EOF'  usage <<END

$(basename $0) <vm-uuid>

Launch a console shell session with an HVM

vm-uuid: The XAPI VM uuid
EOF
END

[[ "$#" != "1" ]] && {
	die "${usage}"
}

DOM_ID=$(xe vm-param-get uuid=$1 param-name=dom-id)
PTY=$(xenstore-read /local/domain/${DOM_ID}/serial/0/tty)
screen ${PTY}
