#!/bin/bash

set -e

IFS='' read -r -d 'EOF'  usage <<END

$(basename $0) <vm-uuid> [--attach-session]

Launch a console shell session with an HVM

vm-uuid: The XAPI VM uuid
attach-session: attach a screen session

EOF
END

VM_ID=$1

[[ "x${VM_ID}" == "x" ]] && {
	die "${usage}"
}

DOM_ID=$(xe vm-param-get uuid=${VM_ID} param-name=dom-id)
PTY=$(xenstore-read /local/domain/${DOM_ID}/serial/0/tty)
echo "DOM_ID=${DOM_ID}"
echo "PTY=${PTY}"

if [[ "$@" =~ "--attach-session" ]];
then
    screen -L ${PTY}
fi
